### PR TITLE
Issue#5 - Option to overwrite default Bitbucket template

### PR DESCRIPTION
**Pull request by OBellon**
I thought something simple like this according to the issue I just submitted.
Let me know what you think.

Thank you so much.

### CODE REVIEW

**Comment by tcrammond** [comment]
Hi

The option is nice. Maybe we should not insert the template at all on the bitbucket 'edit' page, if there's an easy way of detecting it?

**Comment by OBellon** [comment]
Well, the first thing I can think of is looking at the url. If it has something like '/edit/...', do not insert the template again.

If this is not possible, I will go for the checkbox option.

**Comment by OBellon** [comment]
Hi @tcrammond, 

Sorry for the delay, busy days...
In fact, Bitbucket uses '/update/' in the page when editing the pull request, so what about something like

```javascript
if ((isBB || isCustom) && !window.location.href.indexOf('/update')) {
  ...
}
```

Thank you so much!

**Comment by tcrammond** [comment]
Thanks for the contribution. Will have these merged as well as the update thing soon.

**Pull request closed without merging**
